Решил 4 задачи
js-tasks-ru/vue-20230516_andrianov-ov pull request #2
Opened 2023-06-19 17:57 UTC by pow44feet

2023-06-19 17:58 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-06-21 22:02 UTC, ShGKme requested changes
В `01-basics/02-VueCalculator` требуется реализовать вычисление отталкиваясь от состояния. Также требуется убрать лишние обработчики событий и лишнее вычисляемое свойство.

В `01-basics/03-MarkedList` требуются изменения по комментариям.

Пожалуйста, напишите мне, если после комментариев осталось не понятным, почему эти решения требуется изменять или как их изменять.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +          <input type="number" :value="firstNumber" @input="firstNumber = $event.target.value, getCalculate()" />
Вместо привязки значения и обработки события изменения, лучше использовать более удобную и простую директиву двустороннего связывания `v-model`.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +            />
`operator` не может быть обработчиком события `click`, так как это не функция (не метод), это свойство со значение другого свойства - `sign`. Со строкой.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Использовать здесь для получения значения обработку события на форме - неправильно по концепции Vue.

Выбранная операция - это часть состояния приложения. И приложение при вычислении результата должно отталкиваться именно от состояния, а не от кликов пользователя, не от событий в DOM.

Это одна из основных концепций фреймворка. Если отталкиваться от DOM, то при изменении состояния из другого источника, потребуется значительно изменять компонент. За этим нужно следить разработчику. Этой потенциальной проблемы можно избежать, если сразу разрабатывать приложение, отталкиваясь от состояния. Реализация при этом получится даже проще.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Для этого можно сделать `output` не обычным свойством компонента, не данными, а вычисляемым свойством, описав функцию вычисления его значения.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
А это вычисляемое свойство наоборот не требуется. Оно вычисляет всегда `undefined` (так как `sign` не объект, у него нет `value`) и никак не используется в компоненте.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          <input type="search" @input="target = $event.target.value, filter" :value="target" />
Аналогично предыдущей задаче, лучше использовать `v-model`.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Вычисляемые свойства при своём вычислении **ни в коем случае не должны иметь побочных эффектов, не должны изменять состояние, не должны изменять другие свойства или состояние документа**.

Мы не вызываем функцию сами, не контролируем её вызов.

Это также нарушает непосредственно концепцию вычисляемого свойства во Vue о том, что вычисляемое свойство - именно свойство с вычисленным значением.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Но ещё важнее, что во Vue мы никогда не мутируем его DOM вручную. Мы описываем состояние приложение, логику работы приложения вокруг этого состояния и с помощью шаблона - как должно рендериться приложение.

Так мы будем сразу по шаблону видеть, какой на странице будет результат. И при разработке приложения больше не беспокоиться о том, что какие-то данные влияют на этот результат, нужно обновлять DOM в нужных местах.

Помимо концептуальной проблемы, здесь есть и техническая. В этом коде изменяется тот DOM, за который отвечает сам Vue и контролирует сам Vue. При любом полном ререндеринге компонента, не затрагивающего эту функцию, Vue может удалить или сломать весь этот DOM во время рендеринга своего DOM на основе шаблона.

И ещё одна проблема в эффективности. Vue обновляет DOM оптимально. При рендеринге такого списка при изменении фильтра Vue будет только обновлять классы элементами. Здесь же полностью заново пересоздаются DOM элементы.

2023-06-21 22:02 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          <input type="search" @input="target = $event.target.value, filter" :value="target" />
Добавленное через запятую `filter` здесь ничего не делает явно. Но неявно провоцирует вычисление вычисляемого свойства. В итоге есть свойство, значение которого здесь никак не используется, которое не является функцией, но сам факт обращения к котором в перечислении в выражении неявно триггерит вычисление вычисляемого свойства. При чём нужно это всё только 1 раз, при вводе первого символа. Далее вычисляемое свойство будет срабатывать уже за счёт реактивности по факту изменения target.

Такое решение очень не очевидное и не будет работать, если свойство `emails` изменится.

2023-07-08 12:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-09 12:39 UTC, ShGKme approved these changes
Все задачи приняты

2023-07-09 12:39 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
>      },
Здесь хорошо подойдёт метод массива `map` для создания массива, как отображение старого.

Также лучше в данных хранить не имя класса, а флаг маркировки. Чтобы вёрстке не хранилась в вычислениях, а в шаблоне определялось, с какой именно вёрсткой будут промаркированные email-ы.

2023-07-09 12:39 UTC, merged